<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SapientMiddleware</RootNamespace>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	  <AssemblyVersion>3352.5.2.3</AssemblyVersion>
	  <FileVersion>3352.5.2.3</FileVersion>
	<VersionPrefix>5.2.3</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LocationOffsetForm.cs" />
    <Compile Remove="LocationOffsetForm.Designer.cs" />
    <Compile Remove="ServerForm.cs" />
    <Compile Remove="ServerForm.Designer.cs" />
    <Compile Remove="TextForm.cs" />
    <Compile Remove="TextForm.Designer.cs" />
    <Compile Remove="StatusIndicator.cs" />
    <Compile Remove="StatusIndicator.Designer.cs" />
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="LocationOffsetForm.resx" />
    <EmbeddedResource Remove="ServerForm.resx" />
    <EmbeddedResource Remove="TextForm.resx" />
    <EmbeddedResource Remove="StatusIndicator.resx" />
    <EmbeddedResource Remove="Properties\Resources.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Ulid" Version="1.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SapientDatabase\SapientDatabase.csproj" />
    <ProjectReference Include="..\..\SapientServices\SapientServices.csproj" />
  </ItemGroup>

  

</Project>
